name: 'Test the code'

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    strategy:
      fail-fast: true
    name: 'Test the code'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Format
      run: |
        terraform fmt -check -recursive -diff
      working-directory: ./